#!/usr/bin/env bash
set -euo pipefail
source "$ID_ROOT/scripts/lib/common.sh"
source "$ID_ROOT/scripts/lib/paths.sh"
REPORT_PAC_BEFORE=''
REPORT_PAC_AFTER=''
REPORT_HOME_TS=''
REPORT_SYSTEM_TS=''
REPORT_SERVICES_BEFORE=''
REPORT_SERVICES_AFTER=''
REPORT_LOG_FILE=''
REPORT_PROFILE=''
REPORT_TS=''
report_start() {
  local name="$1" reports logs
  REPORT_PROFILE="$name"
  reports="$(profile_reports_dir "$name")"
  logs="$(profile_logs_dir "$name")"
  mkdir -p -- "$reports" "$logs"
  rotate_logs_dir "$logs" 'install-*.log' "$ID_LOG_KEEP_COUNT"
  rotate_logs_dir "$reports" '*.txt' "$((ID_LOG_KEEP_COUNT * 5))"
  rotate_logs_dir "$reports" '*.sh' "$ID_LOG_KEEP_COUNT"
  REPORT_TS="$(date +%Y%m%d-%H%M%S)"
  REPORT_LOG_FILE="$logs/install-$REPORT_TS.log"
  REPORT_PAC_BEFORE="$reports/pacman-before-$REPORT_TS.txt"
  REPORT_PAC_AFTER="$reports/pacman-after-$REPORT_TS.txt"
  REPORT_HOME_TS="$reports/home-before-$REPORT_TS.timestamp"
  REPORT_SYSTEM_TS="$reports/system-before-$REPORT_TS.timestamp"
  REPORT_SERVICES_BEFORE="$reports/services-before-$REPORT_TS.txt"
  REPORT_SERVICES_AFTER="$reports/services-after-$REPORT_TS.txt"
  : > "$REPORT_LOG_FILE"
  touch "$REPORT_HOME_TS"
  if command -v pacman >/dev/null 2>&1; then pacman -Qq > "$REPORT_PAC_BEFORE" 2>/dev/null || true; fi
  if [[ "${ID_TRACK_SYSTEM:-0}" == '1' ]]; then
    touch "$REPORT_SYSTEM_TS" 2>/dev/null || true
    if command -v systemctl >/dev/null 2>&1; then
      systemctl list-unit-files --state=enabled --no-legend 2>/dev/null | awk '{print $1}' | sort -u > "$REPORT_SERVICES_BEFORE" || true
    fi
  fi
}
report_log() { local message="$*"; printf '%s %s\n' "$(timestamp)" "$message" | tee -a "$REPORT_LOG_FILE"; }
_report_write_cleanup_script() {
  local name="$1" script_path="$2" package_diff="$3" system_diff="$4" service_diff="$5"
  {
    printf '#!/usr/bin/env bash\nset -euo pipefail\n\n'
    printf '# Generated by isolated-desktops after installing profile: %s\n' "$name"
    printf '# Review this script manually before running it.\n\n'
    printf 'echo "Host cleanup helper for profile: %s"\n' "$name"
    printf 'echo "This script only contains suggestions for host-wide changes."\n\n'
    if [[ -s "$package_diff" ]]; then
      printf 'echo "Packages installed during profile install:"\n'
      while IFS= read -r pkg; do printf 'echo "  - %s"\n' "$pkg"; done < "$package_diff"
      printf '\nif command -v pacman >/dev/null 2>&1; then\n'
      printf '  echo "Suggested removal command:"\n'
      printf '  echo "  sudo pacman -Rs -- %s"\n' "$(paste -sd' ' "$package_diff")"
      printf 'fi\n\n'
    fi
    if [[ -s "$service_diff" ]]; then
      printf 'echo "Services enabled during profile install:"\n'
      while IFS= read -r svc; do printf 'echo "  - %s"\n' "$svc"; done < "$service_diff"
      printf '\nif command -v systemctl >/dev/null 2>&1; then\n'
      while IFS= read -r svc; do printf '  echo "Suggested: sudo systemctl disable --now %s"\n' "$svc"; done < "$service_diff"
      printf 'fi\n\n'
    fi
    if [[ -s "$system_diff" ]]; then
      printf 'echo "System files modified after install:"\n'
      while IFS= read -r path; do printf 'echo "  - %s"\n' "$path"; done < "$system_diff"
      printf '\necho "Review the paths above and restore from your system backups if needed."\n'
    fi
  } > "$script_path"
  chmod +x "$script_path" || true
}
report_finish() {
  local name="${1:-$REPORT_PROFILE}" reports package_diff changed_home changed_system service_diff cleanup_script
  [[ -n "$name" ]] || return 0
  reports="$(profile_reports_dir "$name")"
  package_diff="$reports/package-diff-$REPORT_TS.txt"
  changed_home="$reports/home-changed-$REPORT_TS.txt"
  changed_system="$reports/system-changed-$REPORT_TS.txt"
  service_diff="$reports/services-enabled-$REPORT_TS.txt"
  cleanup_script="$reports/host-cleanup-$REPORT_TS.sh"
  if command -v pacman >/dev/null 2>&1; then
    pacman -Qq > "$REPORT_PAC_AFTER" 2>/dev/null || true
    if [[ -f "$REPORT_PAC_BEFORE" && -f "$REPORT_PAC_AFTER" ]]; then
      comm -13 <(sort "$REPORT_PAC_BEFORE") <(sort "$REPORT_PAC_AFTER") > "$package_diff" || true
    fi
  fi
  find "$(profile_home_dir "$name")" -type f -newer "$REPORT_HOME_TS" | sort > "$changed_home" || true
  if [[ "${ID_TRACK_SYSTEM:-0}" == '1' && -f "$REPORT_SYSTEM_TS" ]]; then
    find /etc /usr/share -type f -newer "$REPORT_SYSTEM_TS" 2>/dev/null | sort > "$changed_system" || true
    if command -v systemctl >/dev/null 2>&1; then
      systemctl list-unit-files --state=enabled --no-legend 2>/dev/null | awk '{print $1}' | sort -u > "$REPORT_SERVICES_AFTER" || true
      if [[ -f "$REPORT_SERVICES_BEFORE" && -f "$REPORT_SERVICES_AFTER" ]]; then
        comm -13 <(sort "$REPORT_SERVICES_BEFORE") <(sort "$REPORT_SERVICES_AFTER") > "$service_diff" || true
      fi
    fi
  fi
  if [[ -s "$package_diff" || -s "$changed_system" || -s "$service_diff" ]]; then
    _report_write_cleanup_script "$name" "$cleanup_script" "$package_diff" "$changed_system" "$service_diff"
    report_log "Host cleanup helper saved to: $cleanup_script"
  fi
  report_log "Install log saved to: $REPORT_LOG_FILE"
  report_log "Reports saved to: $reports"
}
