#!/usr/bin/env bash
# desktop-launch.sh
#
# Generate /usr/local/bin/start-<name>.sh launch scripts for isolated desktops.
# Each script sets HOME and XDG_* to the fake environment and then execs the
# desktop/WM command.
#
# Version: 1.0
# Author: Vguver
# License: MIT

set -euo pipefail

# -------------------------------------------------------------------
# CONFIGURATION
# -------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source repos module
if [[ ! -f "$SCRIPT_DIR/repos-desktops.sh" ]]; then
  echo "Error: Required file not found: $SCRIPT_DIR/repos-desktops.sh" >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$SCRIPT_DIR/repos-desktops.sh"

CONFIG_BASE_PREFIX="${CONFIG_BASE_PREFIX:-"$HOME/."}"
START_SCRIPTS_DIR="${START_SCRIPTS_DIR:-"/usr/local/bin"}"

# -------------------------------------------------------------------
# HELPER FUNCTIONS
# -------------------------------------------------------------------

# Get fake HOME path
env_path_for() {
  local name="$1"
  printf '%s%s\n' "$CONFIG_BASE_PREFIX" "$name"
}

# Get start script path
start_script_path_for() {
  local name="$1"
  printf '%s/start-%s.sh\n' "$START_SCRIPTS_DIR" "$name"
}

# Validate desktop name
validate_desktop_name() {
  local name="$1"
  
  if [[ -z "$name" ]]; then
    echo "Error: Desktop name cannot be empty" >&2
    return 1
  fi
  
  if [[ ! "$name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "Error: Invalid desktop name: $name" >&2
    return 1
  fi
  
  return 0
}

# Validate command
validate_command() {
  local cmd="$1"
  
  if [[ -z "$cmd" ]]; then
    echo "Error: Command cannot be empty" >&2
    return 1
  fi
  
  # Basic shell command validation
  if [[ "$cmd" =~ [\;\&\|] ]]; then
    echo "Warning: Command contains shell operators (;, &, |)" >&2
    echo "         Make sure this is intentional" >&2
  fi
  
  return 0
}

# Get default desktop command
desktop_default_command() {
  local name="$1"
  
  case "$name" in
    omarchy)       echo "Hyprland" ;;
    jakoolit)      echo "Hyprland" ;;
    dwm-titus)     echo "startx" ;;
    ml4w-starter)  echo "Hyprland" ;;
    ml4w-dotfiles) echo "Hyprland" ;;
    *)
      return 1
      ;;
  esac
}

# -------------------------------------------------------------------
# GENERATE START SCRIPT
# -------------------------------------------------------------------

generate_start_script_content() {
  local name="$1"
  local exec_cmd="$2"
  
  cat <<'EOF'
#!/usr/bin/env bash
# Auto-generated start script for isolated desktop
# Generated by: desktop-launch.sh
# Desktop: DESKTOP_NAME
# Command: EXEC_CMD

set -euo pipefail

# Configuration
DESKTOP_NAME="DESKTOP_NAME"
CONFIG_BASE_PREFIX="${CONFIG_BASE_PREFIX:-$HOME/.}"
ENV_HOME="${CONFIG_BASE_PREFIX}${DESKTOP_NAME}"

# XDG directories
ENV_CONFIG="$ENV_HOME/.config"
ENV_DATA="$ENV_HOME/.local/share"
ENV_CACHE="$ENV_HOME/.cache"
ENV_STATE="$ENV_HOME/.local/state"

# Validation
if [[ ! -d "$ENV_HOME" ]]; then
  echo "Error: Environment for '$DESKTOP_NAME' not found" >&2
  echo "       Expected location: $ENV_HOME" >&2
  echo "       Install it first using setup_desktops.sh" >&2
  exit 1
fi

# Ensure XDG directories exist
mkdir -p "$ENV_CONFIG" "$ENV_DATA" "$ENV_CACHE" "$ENV_STATE"

# Set environment variables
export HOME="$ENV_HOME"
export XDG_CONFIG_HOME="$ENV_CONFIG"
export XDG_DATA_HOME="$ENV_DATA"
export XDG_CACHE_HOME="$ENV_CACHE"
export XDG_STATE_HOME="$ENV_STATE"

# Optional: Log startup
LOG_FILE="$ENV_HOME/logs/startup-$(date +%Y%m%d-%H%M%S).log"
mkdir -p "$(dirname "$LOG_FILE")"
{
  echo "=== Desktop Startup Log ==="
  echo "Desktop: $DESKTOP_NAME"
  echo "Time: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "HOME: $HOME"
  echo "Command: EXEC_CMD"
  echo ""
} > "$LOG_FILE"

# Execute desktop command
echo "Starting $DESKTOP_NAME..." | tee -a "$LOG_FILE"
exec EXEC_CMD
EOF

  # Replace placeholders
  sed -e "s/DESKTOP_NAME/$name/g" \
      -e "s|EXEC_CMD|$exec_cmd|g"
}

# -------------------------------------------------------------------
# CREATE START SCRIPT
# -------------------------------------------------------------------

create_start_script() {
  local name="$1"
  local exec_cmd="${2:-}"
  
  # Validate name
  if ! validate_desktop_name "$name"; then
    return 1
  fi
  
  # Check if desktop exists in repos
  if ! repos_has "$name"; then
    echo "Error: No repository named '$name'" >&2
    echo "       Available: $(repos_list_names | tr '\n' ' ')" >&2
    return 1
  fi
  
  # Get command if not provided
  if [[ -z "$exec_cmd" ]]; then
    if exec_cmd="$(desktop_default_command "$name")"; then
      echo "Using default command for '$name': $exec_cmd"
    else
      echo "Error: No default command for '$name'" >&2
      echo "       Please specify command explicitly" >&2
      return 1
    fi
  fi
  
  # Validate command
  if ! validate_command "$exec_cmd"; then
    return 1
  fi
  
  # Check if fake HOME exists
  local env_home
  env_home="$(env_path_for "$name")"
  if [[ ! -d "$env_home" ]]; then
    echo "Warning: Fake HOME does not exist: $env_home" >&2
    echo "         You should install it first: setup_desktops.sh create $name" >&2
    read -r -p "Continue anyway? [y/N]: " ans
    if [[ ! "$ans" =~ ^[Yy]$ ]]; then
      echo "Aborted by user"
      return 1
    fi
  fi
  
  # Generate script
  local script_path tmpfile
  script_path="$(start_script_path_for "$name")"
  tmpfile="$(mktemp)"
  
  if ! generate_start_script_content "$name" "$exec_cmd" > "$tmpfile"; then
    echo "Error: Failed to generate script content" >&2
    rm -f "$tmpfile"
    return 1
  fi
  
  chmod +x "$tmpfile"
  
  # Try to write without sudo first
  if mv "$tmpfile" "$script_path" 2>/dev/null; then
    echo "✓ Created launch script: $script_path"
  else
    # Need sudo for /usr/local/bin
    echo ""
    echo "The script will be installed to: $script_path"
    echo "This location requires sudo access"
    echo ""
    read -r -p "Proceed with sudo? [Y/n]: " ans
    
    if [[ "$ans" =~ ^[Nn]$ ]]; then
      echo "Aborted by user"
      echo "Temporary script saved at: $tmpfile"
      echo "You can manually move it later with:"
      echo "  sudo mv $tmpfile $script_path"
      echo "  sudo chmod +x $script_path"
      return 1
    fi
    
    if ! sudo mv "$tmpfile" "$script_path"; then
      echo "Error: Failed to install script with sudo" >&2
      rm -f "$tmpfile"
      return 1
    fi
    
    if ! sudo chmod +x "$script_path"; then
      echo "Error: Failed to set executable permission" >&2
      return 1
    fi
    
    echo "✓ Created launch script (with sudo): $script_path"
  fi
  
  echo ""
  echo "Usage:"
  echo "  From TTY:  start-$name.sh"
  echo "  From menu: Select '$name (Isolated)' in display manager"
  echo ""
  
  return 0
}

# -------------------------------------------------------------------
# INTERACTIVE MODE
# -------------------------------------------------------------------

create_interactive() {
  echo "=== Create Launch Script ==="
  echo ""
  
  # List available desktops
  echo "Available desktops:"
  local names
  names=$(repos_list_names)
  if [[ -z "$names" ]]; then
    echo "  (none)"
    echo ""
    echo "Add desktops with: repos-desktops.sh add-interactive"
    return 1
  fi
  
  echo "$names" | sed 's/^/  - /'
  echo ""
  
  # Get desktop name
  local name
  read -r -p "Desktop name: " name
  if [[ -z "$name" ]]; then
    echo "Error: Empty name" >&2
    return 1
  fi
  
  if ! validate_desktop_name "$name"; then
    return 1
  fi
  
  if ! repos_has "$name"; then
    echo "Error: Desktop '$name' not found in repositories" >&2
    return 1
  fi
  
  # Get command
  local cmd default_cmd
  if default_cmd="$(desktop_default_command "$name" 2>/dev/null)"; then
    echo ""
    echo "Default command for '$name': $default_cmd"
    read -r -p "Use default command? [Y/n]: " ans
    
    if [[ "$ans" =~ ^[Nn]$ ]]; then
      read -r -p "Enter custom command: " cmd
      if [[ -z "$cmd" ]]; then
        echo "Error: Empty command" >&2
        return 1
      fi
    else
      cmd="$default_cmd"
    fi
  else
    echo ""
    echo "No default command available for '$name'"
    echo "Examples: Hyprland, startx, dbus-run-session Hyprland"
    read -r -p "Enter start command: " cmd
    if [[ -z "$cmd" ]]; then
      echo "Error: Empty command" >&2
      return 1
    fi
  fi
  
  echo ""
  create_start_script "$name" "$cmd"
}

# -------------------------------------------------------------------
# LIST SCRIPTS
# -------------------------------------------------------------------

list_launch_scripts() {
  echo "Launch scripts for isolated desktops:"
  echo ""
  printf "  %-20s %-10s %s\n" "DESKTOP" "STATUS" "SCRIPT PATH"
  printf "  %-20s %-10s %s\n" "-------" "------" "-----------"
  
  for name in $(repos_list_names); do
    local path status
    path="$(start_script_path_for "$name")"
    
    if [[ -x "$path" ]]; then
      status="✓ Ready"
    elif [[ -f "$path" ]]; then
      status="✗ Not exec"
    else
      status="- Missing"
    fi
    
    printf "  %-20s %-10s %s\n" "$name" "$status" "$path"
  done
  
  echo ""
}

# -------------------------------------------------------------------
# REMOVE SCRIPT
# -------------------------------------------------------------------

remove_start_script() {
  local name="$1"
  
  if ! validate_desktop_name "$name"; then
    return 1
  fi
  
  local script_path
  script_path="$(start_script_path_for "$name")"
  
  if [[ ! -f "$script_path" ]]; then
    echo "Error: Script does not exist: $script_path" >&2
    return 1
  fi
  
  echo "This will remove: $script_path"
  read -r -p "Continue? [y/N]: " ans
  
  if [[ ! "$ans" =~ ^[Yy]$ ]]; then
    echo "Aborted by user"
    return 1
  fi
  
  if rm "$script_path" 2>/dev/null; then
    echo "✓ Removed: $script_path"
  else
    if sudo rm "$script_path"; then
      echo "✓ Removed (with sudo): $script_path"
    else
      echo "Error: Failed to remove script" >&2
      return 1
    fi
  fi
  
  return 0
}

# -------------------------------------------------------------------
# CLI INTERFACE
# -------------------------------------------------------------------

show_help() {
  cat <<EOF
Usage: $0 <command> [args]

COMMANDS:
  create <n> [cmd]     Create launch script
  create-interactive      Interactive creation
  list                    List all launch scripts
  show-path <n>        Show script path
  remove <n>           Remove launch script
  help                    Show this help message

EXAMPLES:
  $0 create omarchy Hyprland
  $0 create dwm-titus startx
  $0 create-interactive
  $0 list
  $0 remove omarchy

DESKTOP COMMANDS:
  Hyprland        - For Wayland compositors
  startx          - For X11 window managers
  dbus-run-session Hyprland - With D-Bus session

ENVIRONMENT:
  START_SCRIPTS_DIR       Installation directory
                          (default: /usr/local/bin)
  CONFIG_BASE_PREFIX      Fake HOME prefix
                          (default: \$HOME/.)

OUTPUT:
  Script location: /usr/local/bin/start-<n>.sh

NOTES:
  - Scripts require fake HOME to exist
  - Installation to /usr/local/bin requires sudo
  - Scripts can be run from TTY or display manager

EOF
}

main() {
  local cmd="${1:-}"
  
  case "$cmd" in
    create)
      if [[ -z "${2:-}" ]]; then
        echo "Error: Desktop name required" >&2
        echo "Usage: $0 create <n> [cmd]" >&2
        exit 1
      fi
      create_start_script "${2}" "${3:-}"
      ;;
      
    create-interactive)
      create_interactive
      ;;
      
    list)
      list_launch_scripts
      ;;
      
    show-path)
      if [[ -z "${2:-}" ]]; then
        echo "Error: Desktop name required" >&2
        echo "Usage: $0 show-path <n>" >&2
        exit 1
      fi
      start_script_path_for "$2"
      ;;
      
    remove)
      if [[ -z "${2:-}" ]]; then
        echo "Error: Desktop name required" >&2
        echo "Usage: $0 remove <n>" >&2
        exit 1
      fi
      remove_start_script "$2"
      ;;
      
    ""|help|-h|--help)
      show_help
      ;;
      
    *)
      echo "Error: Unknown command: $cmd" >&2
      echo "Use '$0 help' for usage information" >&2
      exit 1
      ;;
  esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
